name: backend
version: 0.1.0.0
dependencies:
  - aeson
  - base >= 4.7 && < 5
  - persistent
  - persistent-postgresql
  - servant
  - servant-server
  - text
  - warp

executables:
  backend:
    main: Main.hs
    source-dirs: src